SAMPLE_LISTINGS = [
    {
        "source": "olx",
        "listing_id": "001",
        "url": "https://www.olx.pl/d/oferta/1",
        "title": "Yamaha R6 po szlifie",
        "description": "Motocykl po szlifie. Do wymiany owiewki i klamka. Silnik odpala.",
        "price_pln": 18900,
        "image_urls": ["https://example.com/1.jpg"],
        "brand": "Yamaha",
        "model": "R6",
        "year": 2008,
    },
    {
        "source": "olx",
        "listing_id": "002",
        "url": "https://www.olx.pl/d/oferta/2",
        "title": "Suzuki GSX-R 600 uszkodzony",
        "description": "Po szlifie. Owiewki, lusterko, podnozek. Silnik odpala.",
        "price_pln": 14500,
        "image_urls": ["https://example.com/2.jpg"],
        "brand": "Suzuki",
        "model": "GSX-R 600",
        "year": 2007,
    },
    {
        "source": "olx",
        "listing_id": "003",
        "url": "https://www.olx.pl/d/oferta/3",
        "title": "Honda CBR 600 RR po dzwonie",
        "description": "Motocykl po dzwonie, krzywy przod, lagi, rama. Nie odpala.",
        "price_pln": 16000,
        "image_urls": ["https://example.com/3.jpg"],
        "brand": "Honda",
        "model": "CBR 600 RR",
        "year": 2009,
    },
]